apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: md3wt4yyc-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/md3wt4yyc-java-springboot-gitops